version: '3.4'

services:
  grpcservice:
    image: ${DOCKER_REGISTRY-}grpcservice
    build:
      context: .
      dockerfile: GrpcService/Dockerfile

  blazor.server:
    image: ${DOCKER_REGISTRY-}blazorserver
    build:
      context: .
      dockerfile: Blazor/Server/Dockerfile


  blazor.client:
    image: ${DOCKER_REGISTRY-}blazorclient
    build:
      context: .
      dockerfile: Blazor/Client/Dockerfile

