version: '3.4'

services:
  grpcservice:
    image: ${DOCKER_REGISTRY-}grpcservice
    build:
      context: .
      dockerfile: GrpcService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS="https://+:443;http://+:80"
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/GrpcService.pfx
      
    volumes:
      #- ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      #- ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/ 
        - ~/.aspnet/https:/https:ro
    ports:
      - 5298:80
      - 7298:443

      
      
      