version: '3.4'

services:
  grpcservice:
    depends_on: 
      - sql-server
    image: ${DOCKER_REGISTRY-}grpcservice
    build:
      context: .
      dockerfile: GrpcService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS="https://+:443;http://+:80"
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/GrpcService.pfx
      
    volumes:
      #- ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      #- ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/ 
        - ~/.aspnet/https:/https:ro
    ports:
      - 5298:80
      - 7298:443
  
  sql-server: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sql-server
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TestP@ssw0rd
      - MSSQL_PID=Express
    ports:
      - "1441:1433"
      
      
      