version: '3.4'

services:
  ms-sql-server: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    #hostname: sql-server
    #container_name: sql-server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pa55w0rd!"
      MSSQL_PID: Express
    ports:
      - "1433:1433"

  grpcservice:
    #docker build -t grpcservece -f GrpcService\Dockerfile .
    image: ${DOCKER_REGISTRY-}grpcservice
    build:
      context: .
      dockerfile: GrpcService/Dockerfile
    #depends_on: 
    #- ms-sql-server
    environment:
      DBServer: "ms-sql-server"
      ASPNETCORE_ENVIRONMENT : "Development"
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "pa55w0rd!"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/GrpcService.pfx"
      
    volumes:
      #- ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      #- ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/ 
        - ~/.aspnet/https:/https:ro
    ports:
      - 5298:80
      - 7298:443
  

      
      
      